# Site settings
title: Testing and Stuff
description: "thoughts and experiments"
url: "https://mockersf.github.io/"
baseurl: "https://mockersf.github.io/"

author:
  name: "François Mockers"
  # email: mockersf@gmail.com
  twitter_username: FrancoisMockers
  github_username: mockersf
  linkedin_profile: françois-mockers-ba50324

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
