# Site settings
title: Testing and Stuff
description: "thoughts and experiments"
# baseurl: "/"

author:
  name: "François Mockers"
  # email: mockersf@gmail.com
  mastodon_username: FrancoisMockers
  mastodon_instance: hachyderm.io
  twitter_username: FrancoisMockers
  github_username: mockersf
  linkedin_profile: françois-mockers
  itchio_profile: vleue
  picture: images/m1.png

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 5
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

collections:
  - presentations
