# Site settings
title: Testing and Stuff
description: 'My thoughts and experiments'
url: 'http://mockersf.github.io/'
baseurl: '/'
google_analytics: 'UA-84705806-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'François Mockers'
  email: mockersf@gmail.com
  twitter_username: FrancoisMockers
  facebook_username: francois.mockers
  github_username: mockersf
  linkedin_username: francois-mockers

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
